flowchart TD
    SdUiActivity -->|Koin| SdUiActivityViewModel
    SdUiActivity --> SdUiScreen
    SdUiActivity --> SdUiScreen2
    SdUiScreen -->|koinViewModel| SdUiViewModel
    SdUiScreen2 -->|koinViewModel| SdUiViewModel2
    SdUiViewModel --> SdUiRepository
    SdUiViewModel --> ComponentParser
    SdUiViewModel2 --> SdUiRepository
    SdUiViewModel2 --> ComponentParser
    SdUiViewModel2 --> GlobalStateManager
    SdUiRepository --> SdUiService
    ComponentParser --> ComponentManager
    ComponentParser --> ActionParser
    ComponentParser --> ValidatorParser
    ActionParser --> ActionManager
    ValidatorParser --> ValidatorManager
    ActionManager --> ContinueAction
    ActionManager --> BackAction
    ActionManager --> CloseAction
    ActionManager --> BusinessSuccessAction
    ValidatorManager --> MinLengthValidator
    ValidatorManager --> AllTrueValidator
    ValidatorManager --> EmailValidator
    ComponentManager --> ButtonComponent
    ComponentManager --> ElevatedButtonComponent
    ComponentManager --> OutlinedButtonComponent
    ComponentManager --> ColumnComponent
    ComponentManager --> RowComponent
    ComponentManager --> TextComponent
    ComponentManager --> TopAppBarComponent
    ComponentManager --> SpacerComponent
    ComponentManager --> TextInputComponent
    ComponentManager --> OutlinedTextInputComponent
    ComponentManager --> LottieAnimationComponent
    ComponentManager --> CreatePasswordComponent
    ButtonComponent -->|uses| Action
    ButtonComponent -->|uses| ComponentStateManager
    TextInputComponent -->|uses| ComponentStateManager
    OutlinedTextInputComponent -->|uses| ComponentStateManager
    CreatePasswordComponent -->|uses| ComponentStateManager
    Validators -->|use| ComponentStateManager
    ContinueAction --> GlobalStateManager
    GlobalStateManager --> SdUiActivityViewModel
